### ISSUE TITLE
请教一下关于你代码里面怎么处理数据集的

### ISSUE THREAD

**Issue by yuxuetr** [OneBugMaker/AET#1]
CWRU： 正常 + 3种故障程度*（外圈+内圈+滚子） = 10种类别

B022: 正常 + 2种故障程度*（外圈+内圈+滚子）= 7种类别
CWRU的10我知道9类异常和正常，
B022是摘掉其中的一种么，比如7密耳的？
这段代码是什么含义```
BJUT_SET_NAME = [
                'BJUT_18mN',
                'BJUT_180N',
                'BJUT_15mN',
                'BJUT_150N',]

CWRU_SET_NAME = [
                'CWRU_0HP',
                'CWRU_1HP',
                'CWRU_2HP',
                'CWRU_3HP',]
```
另外是已经把原生的*.mat文件转换成`file_type in ['csv', 'jpg', 'both']`,csv,jpg的数据格式了么？
(可以有偿解答)

**Comment by OneBugMaker** [comment]
感谢老哥的提问。问题我回答在下面了：

### B2022 = BJUT 数据集
我们实验室在2022年收集了一个新的轴承故障数据集BJUT。涉及到的轴承故障类型在论文（G. Wang, D. Liu and L. Cui, "Auto-Embedding Transformer for Interpretable Few-Shot Fault Diagnosis of Rolling Bearings," in IEEE Transactions on Reliability, doi: 10.1109/TR.2023.3328597.） 的TABLE I中有详细的介绍。

### 代码含义
在BJUT_SET_NAME 中:
    下划线前代表数据集的名字，
    下划线后的前两位代表转速：18=1800RPM，15=1500RPM。
    后两位代表径向力：0N=无径向力，mN=1.1kN的径向力。
    BJUT_18mN = BJUT数据集中，在工况1800RPM+1.1kN情况下的数据。
    BJUT_150N = BJUT数据集中，在工况1500RPM+0kN情况下的数据。


在CWRU_SET_NAME 中:
    下划线前代表数据集的名字，下划线后代表 0/1/2/3 HP的工况。

### 数据格式
实验中，BJUT和CWRU两个数据集中的振动信号都被切分成长度为2048的子信号了，
然后，子信号以csv格式储存。

**Comment by yuxuetr** [comment]
是否可以留个联系方式

**Comment by yuxuetr** [comment]
特别感谢。
我下载不到"Auto-Embedding Transformer for Interpretable Few-Shot Fault Diagnosis of Rolling Bearings"的论文，目前是参考其他的一种方法，把振动波通过短时傅里叶变换变成一张2维图像。然后使用ViT的方式进行分类。

**Comment by OneBugMaker** [comment]
感谢提问！
数据预处理部分，请参考：https://github.com/OneBugMaker/Signal-preprocessing

**Comment by yuxuetr** [comment]
万分感谢。
